### ISSUE TITLE
AttributeError: 'Mqtt' object has no attribute 'client'

### ISSUE THREAD

**Issue by njerig** [stlehmann/Flask-MQTT#25]
This error occurs when I try to use the `init_app()` function.

Full error:
```
 * Serving Flask-SocketIO app "sos"
Traceback (most recent call last):
  File "/Users/njerig/.virtualenvs/sosenv/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/Users/njerig/.virtualenvs/sosenv/lib/python3.6/site-packages/flask/cli.py", line 513, in main
    cli.main(args=args, prog_name=name)
  File "/Users/njerig/.virtualenvs/sosenv/lib/python3.6/site-packages/flask/cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/Users/njerig/.virtualenvs/sosenv/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/njerig/.virtualenvs/sosenv/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/njerig/.virtualenvs/sosenv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/njerig/.virtualenvs/sosenv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/njerig/.virtualenvs/sosenv/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/Users/njerig/.virtualenvs/sosenv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/njerig/.virtualenvs/sosenv/lib/python3.6/site-packages/flask_socketio/cli.py", line 68, in run
    run_server()
  File "/Users/njerig/.virtualenvs/sosenv/lib/python3.6/site-packages/flask_socketio/cli.py", line 53, in run_server
    app = info.load_app()
  File "/Users/njerig/.virtualenvs/sosenv/lib/python3.6/site-packages/flask/cli.py", line 237, in load_app
    rv = locate_app(self.app_import_path)
  File "/Users/njerig/.virtualenvs/sosenv/lib/python3.6/site-packages/flask/cli.py", line 90, in locate_app
    __import__(module)
  File "/Users/njerig/code/sos-server/sos.py", line 1, in <module>
    from app import create_app
  File "/Users/njerig/code/sos-server/app/__init__.py", line 29, in <module>
    from app import routes
  File "/Users/njerig/code/sos-server/app/routes.py", line 39, in <module>
    @mqtt.on_message()
  File "/Users/njerig/.virtualenvs/sosenv/lib/python3.6/site-packages/flask_mqtt/__init__.py", line 290, in decorator
    self.client.on_message = handler
AttributeError: 'Mqtt' object has no attribute 'client'
```

run.py
```
from app import create_app

app = create_app

if __name__ == '__main__':
    app.run()
```
app/\__init\__.py
```
from flask import Flask
from flask_mqtt import Mqtt
from config import Config, DevelopmentConfig, TestingConfig

mqtt = Mqtt()

def create_app():
    app = Flask(__name__)
    app.config.from_object(DevelopmentConfig)
    mqtt.init_app(app)

    @app.route('/')
    def index():
        return render_template('index.html')

    return app


from app import mqtt_handlers
```

app/mqtt_handlers.py
```
from app import mqtt
...
@mqtt.on_message()
def handle_mqtt_message(client, userdata, msg):
    ...
```

**Comment by AhnSeongHyun** [comment]
Do you get an error immediately after `python3 run.py`?

In run.py, `app = create_app()` not `app = create_app`

**Comment by njerig** [comment]
Sorry, I do have it as `app = create_app()`. Just missed it while copying and pasting.

**Comment by stlehmann** [comment]
@njerig Could you please supply your config file as well.

**Comment by njerig** [comment]
Sure, here's config.py
```
class Config(object):
    DEBUG = False
    TESTING = False

    SECRET_KEY = 'not-a-safe-secret'

    MQTT_BROKER_URL = 'localhost'
    MQTT_BROKER_PORT = 1883
    MQTT_USERNAME = ''
    MQTT_PASSWORD = ''
    MQTT_KEEPALIVE = 5
    MQTT_TLS_ENABLED = False

class DevelopmentConfig(Config):
    DEBUG = True

class TestingConfig(Config):
    TESTING = True
```

**Comment by stlehmann** [comment]
This happens because you import the mqtt_handlers before the Mqtt object has been initialized via `mqtt.init_app(app)`. Try to put `from app import mqtt_handlers` in your `create_app()` function.

**Comment by njerig** [comment]
That fixed it. Thanks guys!

**Comment by piaca** [comment]
so good
