### ISSUE TITLE
AttributeError: Mqtt instance has no attribute 'client'

### ISSUE THREAD

**Issue by yabb85** [stlehmann/Flask-MQTT#40]
I use Mqtt with init_app and flask_script but an error is displayed during start of flask server.

Traceback (most recent call last):
  File "manager.py", line 10, in <module>
    from project import create_app
  File "/home/test/projecti/project/__init__.py", line 19, in <module>
    from .mqtt import mqtt
  File "/home/test/project/project/mqtt.py", line 33, in <module>
    @mqtt.on_message()
  File "/home/test/.local/share/virtualenvs/project/lib/python2.7/site-packages/flask_mqtt/__init__.py", line 373, in decorator
    self.client.on_message = handler
AttributeError: Mqtt instance has no attribute 'client'

**Comment by deepinder19** [comment]
from just the error above, I think whats wrong is that you are importing `from .mqtt import mqtt` before initializing mqtt init_app. You may want to import/define this after `mqtt.init_app(app)`

**Comment by yabb85** [comment]
Thanks for your explanation.
How to use the splitted project with flask_script extension and create_app function, please?
Thank you.

**Comment by stlehmann** [comment]
@yabb85 Can you give a minmal code sample that shows your use-case.

**Comment by stlehmann** [comment]
This is solved with PR #41
