### ISSUE TITLE
eventlet.hubs.IOClosed: [Errno 107] Operation on closed file

### ISSUE THREAD

**Issue by ffleandro** [stlehmann/Flask-MQTT#74]
Every now and then I get this error after on connect, when I restart my flask app:

```
DEBUG 2020-06-11 16:47:19,008 Thread-2 __init__.py::handle_logging (65): MQTT Log [16]: Sending CONNECT (u1, p1, wr0, wq0, wf0, c1, k60) client_id=b''
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3428, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1801, in loop_forever
    self._reconnect_wait()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3449, in _reconnect_wait
    time.sleep(min(remaining, 1))
  File "/usr/local/lib/python3.8/site-packages/eventlet/greenthread.py", line 36, in sleep
    hub.switch()
  File "/usr/local/lib/python3.8/site-packages/eventlet/hubs/hub.py", line 298, in switch
    return self.greenlet.switch()
eventlet.hubs.IOClosed: [Errno 107] Operation on closed file
```

I'm using Gunicorn to start the flask application and I tried both with and without `eventlet.monkey_patch()`
In all tests I had evenlet installed as a dependency.

Anything I'm doing wrong?

**Comment by stlehmann** [comment]
@ffleandro Did you solve this issue in the meantime? The issue could be related to you using multiple worker threads.
